name: Tag on update
on:
  schedule:
  - cron: '*/5 * * * *'
jobs:
  tag-on-update:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write
    steps:
    - id: fetch-zfs-version
      run: |
        ZFS_URL="$(curl --head https://github.com/openzfs/zfs/releases/latest --output /dev/null --silent --write-out '%{redirect_url}' --fail)"
        ZFS_VERSION="${ZFS_URL##*zfs-}"
        printf 'ZFS_VERSION=%s\n' "$ZFS_VERSION" >>"$GITHUB_OUTPUT"
      background: true
    - id: fetch-versions
      uses: docker://quay.io/fedora/fedora-coreos:stable
      with:
        entrypoint: sh
        args: -c ". /etc/os-release && printf 'BASE_IMAGE_VERSION=%s\nKERNEL_VERSION=%s\n' \"$IMAGE_VERSION\" \"$(/bin/rpm --query --all --queryformat '%{VERSION}-%{RELEASE}' kernel)\" >>\"$GITHUB_OUTPUT\""
      background: true
    - wait:
      - fetch-zfs-version
      - fetch-versions
    - id: generate-tags
      run: |
        printf 'TAG=%s\n' 'fedora-coreos-${{ steps.fetch-versions.outputs.BASE_IMAGE_VERSION }}_kernel-${{ steps.fetch-versions.outputs.KERNEL_VERSION }}_zfs-${{ steps.fetch-zfs-version.outputs.ZFS_VERSION }}' >>"$GITHUB_OUTPUT"
    - id: tag-exists
      run: |
        HTTP_CODE="$(curl --head "${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ steps.generate-tags.outputs.TAG }}" --output /dev/null --write-out '%{http_code}')"
        printf 'HTTP_CODE=%s\n' "$HTTP_CODE" >>"$GITHUB_OUTPUT"
    - id: image-exists
      if: ${{ success() && steps.tag-exists.outputs.HTTP_CODE == 404 }}
      run: |
        curl 'https://ghcr.io/token?scope=repository:ublue-os/akmods-zfs:pull&service=ghcr.io' \
          --output-dir ${{ runner.temp }} \
          --output ublue-os_akmods-zfs_repo_token.response \
          --remote-time \
          --fail
        UBLUE_OS_AKMODS_ZFS_TOKEN="$(jq --raw-output --exit-status '.token' <${{ runner.temp }}/ublue-os_akmods-zfs_repo_token.response)"
        BASE_IMAGE_VERSION='${{ steps.fetch-versions.outputs.BASE_IMAGE_VERSION }}'
        HTTP_CODE="$(curl --head "https://ghcr.io/v2/ublue-os/akmods-zfs/manifests/coreos-stable-${BASE_IMAGE_VERSION%%.*}-${{ steps.fetch-versions.outputs.KERNEL_VERSION }}" \
          -H "Authorization: Bearer $UBLUE_OS_AKMODS_ZFS_TOKEN" \
          -H 'Accept: application/vnd.oci.image.index.v1+json' \
          --write-out '%{http_code}' \
          --output /dev/null)"
        printf 'HTTP_CODE=%s\n' "$HTTP_CODE" >>"$GITHUB_OUTPUT"
    - if: ${{ success() && steps.tag-exists.outputs.HTTP_CODE == 404 && steps.image-exists.outputs.HTTP_CODE == 200 }}
      run: |
        curl -X POST ${{ github.api_url }}/repos/${{ github.repository }}/git/refs \
          -H 'Authorization: Bearer ${{ secrets.RECURSIVE_ACTIONS }}' \
          -H 'Accept: application/vnd.github+json' \
          --data-raw '{"ref":"refs/tags/${{ steps.generate-tags.outputs.TAG }}","sha":"${{ github.sha }}"}' \
          --fail
